# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 18:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Intern', models.IntegerField(default=0)),
                ('POR', models.IntegerField(default=0)),
                ('Training', models.IntegerField(default=0)),
                ('Project', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentIntern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IntProfile', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentExp')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentExp')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPostGrad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpi', models.FloatField()),
                ('ParentBranch', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartDate', models.DateField(blank=True)),
                ('EndDate', models.DateField(blank=True)),
                ('Description', models.TextField()),
                ('ProjectLink', models.TextField(blank=True)),
                ('Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentExp')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Program', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentExp')),
            ],
        ),
        migrations.CreateModel(
            name='StudentUnderGrad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cpi', models.FloatField()),
                ('ParentBranch', models.CharField(max_length=100)),
                ('Institute', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('RollNo', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='XBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('Marks', models.IntegerField()),
                ('Board', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='XIIBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField()),
                ('Board', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DualDegree',
            fields=[
                ('studentundergrad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pas_apis.StudentUnderGrad')),
                ('SecBranch', models.CharField(max_length=100)),
            ],
            bases=('pas_apis.studentundergrad',),
        ),
        migrations.CreateModel(
            name='SecondaryMajor',
            fields=[
                ('studentundergrad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pas_apis.StudentUnderGrad')),
                ('SecBranch', models.CharField(max_length=100)),
            ],
            bases=('pas_apis.studentundergrad',),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('studentuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pas_apis.StudentUser')),
                ('FirstName', models.CharField(blank=True, max_length=100)),
                ('LastName', models.CharField(blank=True, max_length=100)),
                ('MiddleName', models.CharField(blank=True, max_length=100)),
                ('XBoard', models.BooleanField(default=False)),
                ('XIIBoard', models.BooleanField(default=False)),
                ('UnderGrad', models.BooleanField(default=False)),
                ('PostGrad', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('pas_apis.studentuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='xiiboard',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='xboard',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentundergrad',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studenttrain',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentproj',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentpostgrad',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentpor',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentintern',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
        migrations.AddField(
            model_name='studentexp',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pas_apis.StudentProfile'),
        ),
    ]
